services:
db:
image: postgres:latest #currently 18
container_name: marketplace_db
restart: unless-stopped
environment:
  POSTGRES_DB: marketplace
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password #change this in production
ports:
  - "5432:5432"
volumes:
  - marketplace_pdata:/var/lib/postgresql/data

server:
  build:
    context: ./server
  container_name: marketplace_server
  restart: unless-stopped
  ports:
    - "4000:4000"
  environment:
    NODE_ENV: development
    PORT: 4000
    DATABASE_URL: postgres://postgres:password@db:5432/marketplace
  depends_on:
    - db
  volumes:
  - ./server:/app
  - /app/node_modules
  command: npm run dev

volumes:
  marketplace_pgdata:
